version: "3.5"
services:
  staking:
    build:
      context: staking
      args:
        UPSTREAM_VERSION: v0.2.9
    restart: unless-stopped
    environment:
      SIGNER_OPERATIONAL_ADDRESS: ""
      SIGNER_PRIVATE_KEY: ""
      PROVIDER_HTTP_URL: ""
      PROVIDER_WS_URL: ""
      LOG_LEVEL: info
      METRICS_PORT: 9096
