version: "3.5"
services:
  staking:
    build:
      context: staking
      args:
        UPSTREAM_VERSION: v0.3.0
    restart: unless-stopped
    environment:
      SIGNER_OPERATIONAL_ADDRESS: ""
      SIGNER_PRIVATE_KEY: ""
      PROVIDER_HTTP_URL: ""
      PROVIDER_WS_URL: ""
      LOG_LEVEL: info
      METRICS_PORT: 9096
  ui:
    build:
      context: ui
      args:
        VITE_STARKNET_NETWORK: mainnet
        VITE_STARKNET_RPC_URL: /rpc
        VITE_STRK_TOKEN_ADDRESS: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
        VITE_STAKING_CONTRACT_ADDRESS_MAINNET: "0x00ca1702e64c81d9a07b86bd2c540188d92a2c73cf5cc0e508d949015e7e84a7"
        VITE_STAKING_CONTRACT_ADDRESS_SEPOLIA: "0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1"
        VITE_STAKING_MIN_MAINNET: 20000
        VITE_STAKING_MIN_SEPOLIA: 1
    restart: unless-stopped
    environment:
      PROVIDER_HTTP_URL: ""
    networks:
      - dncore_network
networks:
  dncore_network:
    external: true
