version: "3.5"
services:
  staking:
    build:
      context: staking
      args:
        UPSTREAM_VERSION: v0.2.7
    environment:
      PROVIDER_HTTP_URL: "http://execution.starknet-sepolia.staker.dappnode:6060/v0_9"
      PROVIDER_WS_URL: "ws://execution.starknet-sepolia.staker.dappnode:6061/v0_9"
  ui:
    build:
      args:
        VITE_STARKNET_NETWORK: sepolia
    environment:
      RPC_TARGET: "http://execution.starknet-sepolia.staker.dappnode:6060/v0_9"
    networks:
      - dncore_network
networks:
  dncore_network:
    external: true
