version: "3.5"
services:
  staking:
    build:
      context: staking
      args:
        UPSTREAM_VERSION: v0.2.7
    environment:
      PROVIDER_HTTP_URL: "http://juno.dappnode:6060/v0_8"
      PROVIDER_WS_URL: "ws://juno.dappnode:6061/v0_8"
      METRICS_PORT: 9096
